name: Ci express project

on: 
  push: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Format Code
        run: npm run format

      - name: Check for Formatting Changes
        run: |
          if ! git diff --quiet; then
            echo "needs_commit=true" >> $GITHUB_ENV
          else 
            echo "needs_commit=false" >> $GITHUB_ENV
          fi

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Formatting Changes
        if: env.needs_commit == 'true'
        run: |
          git add .
          git commit -m "Auto-format code in Express Project"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Generate Swagger JSON
        run: npx ts-node src/swagger.ts

      - name: Commit and push Swagger file
        run: |
          git add .
          git commit -m "Generate Swagger docs by Github Actions Bot" || echo "No changes to commit"
          git push 

      - name: Build project
        run: npm run build

  build_docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file in CI
        run: |
           echo "${{vars.PORT}}" > .env
           echo "${{vars.BASE_URL}}" > .env
           echo ${{toJson(vars.PORT)}}
           echo ${{toJson(env.PORT)}}
           echo ${{toJson(secrets.PORT)}}
           echo ${{toJson(vars.app-env)}}
           echo ${{toJson(env.app-env)}}
           echo ${{toJson(secrets.app-env)}}
      
      - name: Build and run docker compose 
        run: docker-compose up -d --build

      - name: Wait for Containers to Start
        run: sleep 10

      - name: Show Running Containers
        run: docker ps -a

      - name: Show Logs of Running Containers
        run: docker-compose logs

      - name: Stop docker compose
        run: docker-compose down
        