name: Ci express project

on: 
   push: 
    branches: 
        main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install nodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: npm

            - name: Install dependencies
              run: npm ci
            
            - name: Format Code
              run: npm run format

            - name: Check for Formatting Changes
              run: git diff --exit-code || echo "needs-commit=true" >> $GITHUB_ENV

            - name: Commit Formatting Changes
              if: env.needs-commit == 'true'
              run:  
                 git config --global user.name "github-actions[bot]"
                 git config --global user.email "github-actions[bot]@users.noreply.github.com"
                 git add .
                 git commit -m "Auto-format code in Express Project"
                 git push
            
            - name: Build project
              run: npm run build