name: Deploy Express Project
on: [push ,workflow_dispatch]

jobs:
    test:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest , windows-latest]
          node_version: [16 ,18 ,20 ,22]
      runs-on: ${{ matrix.os }}
      steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install Nodejs
            uses: actions/setup-node@v4
            with:
              node-version: ${{matrix.node_version}}
          - name: Cache dependencies
            uses: actions/cache@v4
            with:
              path: ~/.npm
              key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
          - name: Install dependencies
            run: npm ci

    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Cache dependencies
            uses: actions/cache@v4
            with:
              path: ~/.npm
              key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
          - name: Install dependencies
            run: npm ci
          - name: Get build artifacts
            uses: actions/download-artifact@v4
            with: 
              name: dist-files
          - name: Output contents
            run: ls
          - name: Deploy
            run: echo "Deploying...." && exit 1 && echo "Deployed success. Server running on port ${{env.PORT}}"
    report:
      needs: [deploy, test]
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Output information
          run: |
            echo "Something want wrong"
            echo "${{ toJson(github) }}"