name: Reusable workflow

on:
    workflow_call

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist