name: Reusable workflow

on:
    workflow_call:
        inputs:
          artifact-name: 
            description: The name of the deployment artifact file
            required: false
            default: dist
            type: string
          artifact-path:
            description: The path of deployment artifact file
            required: false
            default: dist-files
            type: string

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{inputs.artifact-name}}
            path: ${{inputs.artifact-path}}